const gojuonSheet = [
  {
    alphabetical: 'a',
    text: ['あ','ア'],
    dakuon: false,
    handak: false,
    youon: false,
  },
  {
    alphabetical: 'i',
    text: ['い','イ'],
    dakuon: false,
    handak: false,
    youon: false,
  },
  {
    alphabetical: 'u',
    text: ['う','ウ'],
    dakuon: false,
    handak: false,
    youon: false,
  },
  {
    alphabetical: 'e',
    text: ['え','エ'],
    dakuon: false,
    handak: false,
    youon: false,
  },
  {
    alphabetical: 'o',
    text: ['お','オ'],
    dakuon: false,
    handak: false,
    youon: false,
  },
  {
    alphabetical: 'ka',
    text: ['か','カ'],
    dakuon: false,
    handak: false,
    youon: false,
  },
  {
    alphabetical: 'ki',
    text: ['き','キ'],
    dakuon: false,
    handak: false,
    youon: false,
  },
  {
    alphabetical: 'ku',
    text: ['く','ク'],
    dakuon: false,
    handak: false,
    youon: false,
  },
  {
    alphabetical: 'ke',
    text: ['け','ケ'],
    dakuon: false,
    handak: false,
    youon: false,
  },
  {
    alphabetical: 'ko',
    text: ['こ','コ'],
    dakuon: false,
    handak: false,
    youon: false,
  },
  {
    alphabetical: 'sa',
    text: ['さ','サ'],
    dakuon: false,
    handak: false,
    youon: false,
  },
  {
    alphabetical: 'shi',
    text: ['し','シ'],
    dakuon: false,
    handak: false,
    youon: false,
  },
  {
    alphabetical: 'su',
    text: ['す','ス'],
    dakuon: false,
    handak: false,
    youon: false,
  },
  {
    alphabetical: 'se',
    text: ['せ','セ'],
    dakuon: false,
    handak: false,
    youon: false,
  },
  {
    alphabetical: 'so',
    text: ['そ','ソ'],
    dakuon: false,
    handak: false,
    youon: false,
  },
  {
    alphabetical: 'ta',
    text: ['た','タ'],
    dakuon: false,
    handak: false,
    youon: false,
  },
  {
    alphabetical: 'chi',
    text: ['ち','チ'],
    dakuon: false,
    handak: false,
    youon: false,
  },
  {
    alphabetical: 'tsu',
    text: ['つ','ツ'],
    dakuon: false,
    handak: false,
    youon: false,
  },
  {
    alphabetical: 'te',
    text: ['て','テ'],
    dakuon: false,
    handak: false,
    youon: false,
  },
  {
    alphabetical: 'to',
    text: ['と','ト'],
    dakuon: false,
    handak: false,
    youon: false,
  },
  {
    alphabetical: 'na',
    text: ['な','ナ'],
    dakuon: false,
    handak: false,
    youon: false,
  },
  {
    alphabetical: 'ni',
    text: ['に','ニ'],
    dakuon: false,
    handak: false,
    youon: false,
  },
  {
    alphabetical: 'nu',
    text: ['ぬ','ヌ'],
    dakuon: false,
    handak: false,
    youon: false,
  },
  {
    alphabetical: 'ne',
    text: ['ね','ネ'],
    dakuon: false,
    handak: false,
    youon: false,
  },
  {
    alphabetical: 'no',
    text: ['の','ノ'],
    dakuon: false,
    handak: false,
    youon: false,
  },
  {
    alphabetical: 'ha',
    text: ['は','ハ'],
    dakuon: false,
    handak: false,
    youon: false,
  },
  {
    alphabetical: 'hi',
    text: ['ひ','ヒ'],
    dakuon: false,
    handak: false,
    youon: false,
  },
  {
    alphabetical: 'fu',
    text: ['ふ','フ'],
    dakuon: false,
    handak: false,
    youon: false,
  },
  {
    alphabetical: 'he',
    text: ['へ','ヘ'],
    dakuon: false,
    handak: false,
    youon: false,
  },
  {
    alphabetical: 'ho',
    text: ['ほ','ホ'],
    dakuon: false,
    handak: false,
    youon: false,
  },
  {
    alphabetical: 'ma',
    text: ['ま','マ'],
    dakuon: false,
    handak: false,
    youon: false,
  },
  {
    alphabetical: 'mi',
    text: ['み','ミ'],
    dakuon: false,
    handak: false,
    youon: false,
  },
  {
    alphabetical: 'mu',
    text: ['む','ム'],
    dakuon: false,
    handak: false,
    youon: false,
  },
  {
    alphabetical: 'me',
    text: ['め','メ'],
    dakuon: false,
    handak: false,
    youon: false,
  },
  {
    alphabetical: 'mo',
    text: ['も','モ'],
    dakuon: false,
    handak: false,
    youon: false,
  },
  {
    alphabetical: 'ya',
    text: ['や','ヤ'],
    dakuon: false,
    handak: false,
    youon: false,
  },
  {
    alphabetical: 'yu',
    text: ['ゆ','ユ'],
    dakuon: false,
    handak: false,
    youon: false,
  },
  {
    alphabetical: 'yo',
    text: ['よ','ヨ'],
    dakuon: false,
    handak: false,
    youon: false,
  },
  {
    alphabetical: 'ra',
    text: ['ら','ラ'],
    dakuon: false,
    handak: false,
    youon: false,
  },
  {
    alphabetical: 'ri',
    text: ['り','リ'],
    dakuon: false,
    handak: false,
    youon: false,
  },
  {
    alphabetical: 'ru',
    text: ['る','ル'],
    dakuon: false,
    handak: false,
    youon: false,
  },
  {
    alphabetical: 're',
    text: ['れ','レ'],
    dakuon: false,
    handak: false,
    youon: false,
  },
  {
    alphabetical: 'ro',
    text: ['ろ','ロ'],
    dakuon: false,
    handak: false,
    youon: false,
  },
  {
    alphabetical: 'wa',
    text: ['わ','ワ'],
    dakuon: false,
    handak: false,
    youon: false,
  },
  {
    alphabetical: 'wi',
    text: ['ゐ','ヰ'],
    dakuon: false,
    handak: false,
    youon: false,
  },
  {
    alphabetical: 'we',
    text: ['ゑ','ヱ'],
    dakuon: false,
    handak: false,
    youon: false,
  },
  {
    alphabetical: 'wo',
    text: ['を','ヲ'],
    dakuon: false,
    handak: false,
    youon: false,
  },
  {
    alphabetical: 'n',
    text: ['ん','ン'],
    dakuon: false,
    handak: false,
    youon: false,
  },
  {
    alphabetical: 'ga',
    text: ['が','ガ'],
    dakuon: true,
    handak: false,
    youon: false,
  },
  {
    alphabetical: 'gi',
    text: ['ぎ','ギ'],
    dakuon: true,
    handak: false,
    youon: false,
  },
  {
    alphabetical: 'ge',
    text: ['げ','ゲ'],
    dakuon: true,
    handak: false,
    youon: false,
  },
  {
    alphabetical: 'go',
    text: ['ご','ゴ'],
    dakuon: true,
    handak: false,
    youon: false,
  },
  {
    alphabetical: 'za',
    text: ['ざ','ザ'],
    dakuon: true,
    handak: false,
    youon: false,
  },
  {
    alphabetical: 'ji',
    text: ['じ','ジ'],
    dakuon: true,
    handak: false,
    youon: false,
  },
  {
    alphabetical: 'zu',
    text: ['ず','ズ'],
    dakuon: true,
    handak: false,
    youon: false,
  },
  {
    alphabetical: 'ze',
    text: ['ぜ','ゼ'],
    dakuon: true,
    handak: false,
    youon: false,
  },
  {
    alphabetical: 'zo',
    text: ['ぞ','ゾ'],
    dakuon: true,
    handak: false,
    youon: false,
  },
  {
    alphabetical: 'da',
    text: ['だ','ダ'],
    dakuon: true,
    handak: false,
    youon: false,
  },
  {
    alphabetical:"di",
    text:['ぢ','ヂ'],
    dakuon: true,
    handak: false,
    youon: false,
  },
  {
    alphabetical:'du',
    text:['づ','ヅ'],
    dakuon: true,
    handak: false,
    youon: false,
  },
  {
    alphabetical:'de',
    text:['で','デ'],
    dakuon: true,
    handak: false,
    youon: false,
  },
  {
    alphabetical:'do',
    text:[',ど','ド'],
    dakuon: true,
    handak: false,
    youon: false,
  },
  {
    alphabetical:'ba',
    text:['ば','バ'],
    dakuon: true,
    handak: false,
    youon: false,
  },
  {
    alphabetical:'bi',
    text:['び','ビ'],
    dakuon: true,
    handak: false,
    youon: false,
  },
  {
    alphabetical:'bu',
    text:['ぶ','ブ'],
    dakuon: true,
    handak: false,
    youon: false,
  },
  {
    alphabetical:'be',
    text:['べ','ベ'],
    dakuon: true,
    handak: false,
    youon: false,
  },
  {
    alphabetical:'bo',
    text:['ぼ','ボ'],
    dakuon: true,
    handak: false,
    youon: false,
  },
  {
    alphabetical: 'pa',
    text:['ぱ','パ'],
    dakuon: false,
    handak: true,
    youon: false,
  },
  {
    alphabetical: 'pi',
    text:['ぴ','ピ'],
    dakuon: false,
    handak: true,
    youon: false,
  },
  {
    alphabetical: 'pu',
    text:['ぷ','プ'],
    dakuon: false,
    handak: true,
    youon: false,
  },
  {
    alphabetical: 'pe',
    text:['ぺ','ペ'],
    dakuon: false,
    handak: true,
    youon: false,
  },
  {
    alphabetical: 'po',
    text:['ぽ','ポ'],
    dakuon: false,
    handak: true,
    youon: false,
  },
  {
    alphabetical: 'kya',
    text:['きゃ','キャ'],
    dakuon: false,
    handak: false,
    youon: true,
  },
  {
    alphabetical: 'kyu',
    text:['きゅ','キュ'],
    dakuon: false,
    handak: false,
    youon: true,
  },
  {
    alphabetical: 'kyo',
    text:['きょ','キョ'],
    dakuon: false,
    handak: false,
    youon: true,
  },
  {
    alphabetical: 'gya',
    text:['ぎゃ','ギャ'],
    dakuon: false,
    handak: false,
    youon: true,
  },
  {
    alphabetical: 'gyu',
    text:['ぎゅ','ギュ'],
    dakuon: false,
    handak: false,
    youon: true,
  },
  {
    alphabetical: 'gyo',
    text:['ぎょ','ギョ'],
    dakuon: false,
    handak: false,
    youon: true,
  },
  {
    alphabetical: 'sya',
    text:['しゃ','シャ'],
    dakuon: false,
    handak: false,
    youon: true,
  },
  {
    alphabetical: 'syu',
    text:['しゅ','シュ'],
    dakuon: false,
    handak: false,
    youon: true,
  },
  {
    alphabetical: 'syo',
    text:['しょ','ショ'],
    dakuon: false,
    handak: false,
    youon: true,
  },
  {
    alphabetical: 'ja',
    text:['じゃ','ジャ'],
    dakuon: false,
    handak: false,
    youon: true,
  },
  {
    alphabetical: 'ju',
    text:['じゅ','ジュ'],
    dakuon: false,
    handak: false,
    youon: true,
  },
  {
    alphabetical: 'jo',
    text:['じょ','ジョ'],
    dakuon: false,
    handak: false,
    youon: true,
  },
  {
    alphabetical: 'cha',
    text:['ちゃ','チャ'],
    dakuon: false,
    handak: false,
    youon: true,
  },
  {
    alphabetical: 'chu',
    text:['ちゅ','チュ'],
    dakuon: false,
    handak: false,
    youon: true,
  },
  {
    alphabetical: 'cho',
    text:['ちょ','チョ'],
    dakuon: false,
    handak: false,
    youon: true,
  },
  {
    alphabetical: 'dya',
    text:['ぢゃ','ヂャ'],
    dakuon: false,
    handak: false,
    youon: true,
  },
  {
    alphabetical: 'dyu',
    text:['ぢゅ','ヂュ'],
    dakuon: false,
    handak: false,
    youon: true,
  },
  {
    alphabetical: 'dyo',
    text:['ぢょ','ヂョ'],
    dakuon: false,
    handak: false,
    youon: true,
  },
  {
    alphabetical: 'nya',
    text:['にゃ','ニャ'],
    dakuon: false,
    handak: false,
    youon: true,
  },
  {
    alphabetical: 'nyu',
    text:['にゅ','ニュ'],
    dakuon: false,
    handak: false,
    youon: true,
  },
  {
    alphabetical: 'nyo',
    text:['にょ','ニョ'],
    dakuon: false,
    handak: false,
    youon: true,
  },
  {
    alphabetical: 'hya',
    text:['ひゃ','ヒャ'],
    dakuon: false,
    handak: false,
    youon: true,
  },
  {
    alphabetical: 'hyu',
    text:['ひゅ','ヒュ'],
    dakuon: false,
    handak: false,
    youon: true,
  },
  {
    alphabetical: 'hyo',
    text:['ひょ','ヒョ'],
    dakuon: false,
    handak: false,
    youon: true,
  },
  {
    alphabetical: 'bya',
    text:['びゃ','ビャ'],
    dakuon: false,
    handak: false,
    youon: true,
  },
  {
    alphabetical: 'byu',
    text:['びゅ','ビュ'],
    dakuon: false,
    handak: false,
    youon: true,
  },
  {
    alphabetical: 'byo',
    text:['びょ','ビョ'],
    dakuon: false,
    handak: false,
    youon: true,
  },
  {
    alphabetical: 'pya',
    text:['ぴゃ','ピャ'],
    dakuon: false,
    handak: false,
    youon: true,
  },
  {
    alphabetical: 'pyu',
    text:['ぴゅ','ピュ'],
    dakuon: false,
    handak: false,
    youon: true,
  },
  {
    alphabetical: 'pyo',
    text:['ぴょ','ピョ'],
    dakuon: false,
    handak: false,
    youon: true,
  },
  {
    alphabetical: 'mya',
    text:['みゃ','ミャ'],
    dakuon: false,
    handak: false,
    youon: true,
  },
  {
    alphabetical: 'myu',
    text:['みゅ','ミュ'],
    dakuon: false,
    handak: false,
    youon: true,
  },
  {
    alphabetical: 'myo',
    text:['みょ','ミョ'],
    dakuon: false,
    handak: false,
    youon: true,
  },
  {
    alphabetical: 'rya',
    text:['りゃ','リャ'],
    dakuon: false,
    handak: false,
    youon: true,
  },
  {
    alphabetical: 'ryu',
    text:['りゅ','リュ'],
    dakuon: false,
    handak: false,
    youon: true,
  },
  {
    alphabetical: 'ryo',
    text:['りょ','リョ'],
    dakuon: false,
    handak: false,
    youon: true,
  },
]

const gojuonHelper = {
  getGojuonSheet: () => gojuonSheet,
  getYouonSheet: () => gojuonSheet.filter(item => item.youon),
}





